### ISSUE TITLE
After change config file upload sample form the Execute button not response 

### ISSUE THREAD

**Issue by xiongyunqiang** [fx-giant/giant-documentations#7]
what I do is:
1. pull your sample,zip file and backend service file.
2. deploy the service make sure when open the service with  chrome have response.
3. edit sample.zip file config.json with new GUID, change the serviceUrl to my one.
4. after save upload the sample.zip file to GIANT SIT environment 
5. click the Execute button at the form page not response will show.

I want know is: is it correct ? which part I miss out or not ?

**Comment by hansyulian** [comment]
step number 2: it might be accessible through your chrome, but is it accessible through the GIANT environment you are using? can you tell what is the url you are using to access using chrome?
3. editing to new GUID is fine, the service url is confirmed correct?
4. since you are uploading to SIT environment, the service must be accessible through our BISON environment
5. what is the error message shown?

**Comment by xiongyunqiang** [comment]
it is because my giant cannot connect to my back-end service. thanks
